var rpi=rpi||{};
rpi.Time={getFormatTime:function(a,c,b){a=new Date(this._ms(a));var e=b||"en";b=function(h){return 10>h?"0"+h:""+h};var k=a.getHours(),l=((new Intl.DateTimeFormat(e,{day:"numeric",month:"short"})).formatToParts(a).find(function(h){return"month"===h.type})||{}).value;e=(new Intl.DateTimeFormat(e,{day:"numeric",month:"long"})).formatToParts(a).find(function(h){return"month"===h.type}).value;var u=a.getFullYear(),f=String(u).slice(-2),p={yyyy:u,Y:u,yy:f,y:f,MMMM:e,MMM:l,M:l,MM:b(a.getMonth()+1),m:b(a.getMonth()+
1),dd:b(a.getDate()),d:b(a.getDate()),HH:b(k),H:k,hh:b(k%12||12),h:k%12||12,mm:b(a.getMinutes()),i:b(a.getMinutes()),ss:b(a.getSeconds()),s:b(a.getSeconds()),a:12<=k?"pm":"am",A:12<=k?"PM":"AM"};return c.replace(/(MMMM|MMM|yyyy|HH|hh|MM|mm|dd|ss|yy|H|h|M|m|d|Y|y|i|s|a|A)/g,h=>null!=p[h]?p[h]:h)},getTimeAgo:function(a,c){a=(this._ms(a)-Date.now())/1E3;var b=Math.abs(a);c=new Intl.RelativeTimeFormat(c||"en",{numeric:"auto"});return 60>b?c.format(Math.round(a),"second"):3600>b?c.format(Math.round(a/
60),"minute"):86400>b?c.format(Math.round(a/3600),"hour"):2592E3>b?c.format(Math.round(a/86400),"day"):31536E3>b?c.format(Math.round(a/2592E3),"month"):c.format(Math.round(a/31536E3),"year")},_ms:function(a){a=parseInt(a,10);return 1E10>a?1E3*a:a}};var TrustReviews=TrustReviews||{};TrustReviews.slg="trustreviews";
TrustReviews.Plugin={next:function(a,c){a=this.parentNode;var b="."+TrustReviews.slg+"-hide";reviews=a.querySelectorAll(b);for(var e=0;e<c&&e<reviews.length;e++)reviews[e]&&(reviews[e].className=reviews[e].className.replace(TrustReviews.slg+"-hide"," "));reviews=a.querySelectorAll(b);reviews.length||a.removeChild(this);return!1},leave_popup:function(){TrustReviews.Plugin.popup(this.getAttribute("href"),620,500);return!1},lang:function(){var a=navigator;return(a.language||a.systemLanguage||a.userLanguage||
"en").substr(0,2).toLowerCase()},popup:function(a,c,b,e,k,l){k=k||screen.height/2-b/2;l=l||screen.width/2-c/2;return window.open(a,"","location=1,status=1,resizable=yes,width="+c+",height="+b+",top="+k+",left="+l)},timeago:function(){let a=document.querySelectorAll("."+TrustReviews.slg+" [data-rev]");for(var c=0;c<a.length;c++){let b=a[c].querySelector("[data-time]");b.innerHTML=rpi.Time.getTimeAgo(b.dataset.time,this.lang())}},read_more:function(){for(var a=document.querySelectorAll(".wp-more-toggle"),
c=0;c<a.length;c++)(function(b){b.onclick=function(){b.parentNode.removeChild(b.previousSibling.previousSibling);b.previousSibling.className="";b.textContent=""}})(a[c])},get_parent:function(a,c){c=c||TrustReviews.slg;if(0>a.className.split(" ").indexOf(c))for(;(a=a.parentElement)&&0>a.className.split(" ").indexOf(c););return a},init_slider:function(a,c){function b(d){var g=f("row",1);for(let v=0;v<g.length;v++){let w=g[v],m=w.offsetWidth;var r=510>m?"xs":750>m?"x":1100>m?"s":1450>m?"m":1800>m?"l":
"xl";w.className=a+"-row "+a+"-row-"+r}n.length&&C!=r&&setTimeout(function(){q.scrollLeft!=d*n[0].offsetWidth&&(q.scrollLeft=d*n[0].offsetWidth);e();C=r},200)}function e(){var d=f("reviews"),g=f("review",1),r=Math.round(d.offsetWidth/g[0].offsetWidth),v=Math.ceil(g.length/r),w=f("dots");if(w){w.innerHTML="";for(var m=0;m<v;m++){var y=document.createElement("div");y.className=a+"-dot";x=Math.ceil((d.scrollLeft+(d.scrollLeft+g[0].offsetWidth*r))/2*v/d.scrollWidth);x==m+1&&(y.className=a+"-dot active");
y.setAttribute("data-index",m+1);y.setAttribute("data-visible",r);w.appendChild(y);y.onclick=function(){var z=f("dot.active");z=parseInt(z.getAttribute("data-index"));var B=parseInt(this.getAttribute("data-index")),D=parseInt(this.getAttribute("data-visible"));z<B?l(D*Math.abs(B-z)):k(D*Math.abs(B-z));f("dot.active").className=a+"-dot";this.className=a+"-dot active";t&&clearInterval(t)}}}}function k(d){q.scrollBy(-n[0].offsetWidth*d,0)}function l(d){q.scrollBy(n[0].offsetWidth*d,0)}function u(){var d=
f("review:last-child"),g=d.getBoundingClientRect();d=d.parentNode.getBoundingClientRect();(2>Math.abs(d.left-g.left)||d.left<=g.left)&&g.left<d.right&&(2>Math.abs(d.right-g.right)||d.right>=g.right)&&g.right>d.left?k(n.length-Math.round(q.offsetWidth/n[0].offsetWidth)):l(1);t=setTimeout(u,E)}function f(d,g){return g?c.querySelectorAll("."+a+"-"+d):c.querySelector("."+a+"-"+d)}const p=f("row"),h=JSON.parse(p.getAttribute("data-options")),E=1E3*h.speed,q=f("reviews"),n=f("review",1);var C="",F=null,
t=null,G=function(){(p.offsetWidth||p.offsetHeight||p.getClientRects().length)&&"hidden"!==window.getComputedStyle(p).visibility?(setTimeout(b,1),n.length&&h.autoplay&&setTimeout(u,E)):setTimeout(G,300)};G();window.addEventListener("resize",function(){var d=Math.round(q.scrollLeft/n[0].offsetWidth);clearTimeout(F);F=setTimeout(b,150,d)});q&&q.addEventListener("scroll",function(){setTimeout(e,200)});var A=f("prev");A&&(A.onclick=function(){k(1);t&&clearInterval(t)});if(A=f("next"))A.onclick=function(){l(1);
t&&clearInterval(t)}},init:function(a,c,b){this.timeago();this.read_more();!(c=this.get_parent(c,a))||"true"==c.getAttribute("data-exec")||"slider"!=b&&"grid"!=b||(c.setAttribute("data-exec","true"),this.init_slider(a,c))}};document.addEventListener("DOMContentLoaded",function(){for(var a=document.querySelectorAll("."+TrustReviews.slg+'[data-exec="false"]'),c=0;c<a.length;c++){var b=a[c];TrustReviews.Plugin.init(TrustReviews.slg,b,b.getAttribute("data-layout"))}});
